# Generated by Django 4.1.1 on 2022-10-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtail_sb_socialnetworks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialnetwork",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailimages.image",
                verbose_name="Icon",
            ),
        ),
    ]
