# Generated by Django 4.1.1 on 2022-10-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_sb_socialnetworks", "0002_alter_socialnetwork_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesocialnetworkprofile",
            old_name="sitesettings",
            new_name="site_settings",
        ),
        migrations.AlterUniqueTogether(
            name="sitesocialnetworkprofile",
            unique_together={("site_settings", "profile")},
        ),
    ]
