language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install tox-travis
script:
  - tox
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then tox -e black; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then tox -e codacy; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then tox -e codecov; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then tox -e flake8; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then tox -e pydocstyle; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then tox -e mypy; fi
